# Nostr-rs-relay configuration

[info]
# Using your AWS instance IP
relay_url = "wss://18.221.154.194:7000/"
name = "POWR-nostr-relay"
description = "A private relay for Proof of Workout (POW) - tracking and verifying workout achievements."
contact = "mailto:akirshtein@promotus.io"

[database]
engine = "sqlite"
data_directory = "./db"

[logging]
folder_path = "./log"
file_prefix = "relay-log"

[network]
address = "0.0.0.0"
port = 8080
remote_ip_header = "x-forwarded-for"
ping_interval = 180

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 10
subscriptions_per_min = 30
event_kind_allowlist = [
    0,    # Metadata
    1,    # Short text note
    5,    # Event deletion
    7,    # Reaction
    33,   # Parameterized replaceable events
    30023, # Long-form content
]
max_event_bytes = 131072
max_ws_message_bytes = 131072
max_ws_frame_bytes = 131072
broadcast_buffer = 16384
event_persist_buffer = 4096

[authorization]
nip26_auth = true
nip42_auth = true
nip42_dms = true

[verified_users]
mode = "enabled"
verify_expiration = "1 week"
verify_update_frequency = "24 hours"
max_consecutive_failures = 10