services:
  nostr-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-rs-relay
    ports:
      - "7000:8080"  # Adjusted the exposed ports
    volumes:
      - ./db:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml
      - ./log:/usr/src/app/log
    environment:
      - TZ=Etc/UTC
      - RUST_LOG=info,nostr_rs_relay=info
    command: ./nostr-rs-relay --config /usr/src/app/config.toml
